// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: state.proto

#ifndef PROTOBUF_state_2eproto__INCLUDED
#define PROTOBUF_state_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace vss_state {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_state_2eproto();
void protobuf_AssignDesc_state_2eproto();
void protobuf_ShutdownFile_state_2eproto();

class Ball_State;
class Global_State;
class Pose;
class RGB;
class Robot_State;

// ===================================================================

class RGB : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:vss_state.RGB) */ {
 public:
  RGB();
  virtual ~RGB();

  RGB(const RGB& from);

  inline RGB& operator=(const RGB& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const RGB& default_instance();

  void Swap(RGB* other);

  // implements Message ----------------------------------------------

  inline RGB* New() const { return New(NULL); }

  RGB* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const RGB& from);
  void MergeFrom(const RGB& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(RGB* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 r = 1;
  bool has_r() const;
  void clear_r();
  static const int kRFieldNumber = 1;
  ::google::protobuf::uint32 r() const;
  void set_r(::google::protobuf::uint32 value);

  // required uint32 g = 2;
  bool has_g() const;
  void clear_g();
  static const int kGFieldNumber = 2;
  ::google::protobuf::uint32 g() const;
  void set_g(::google::protobuf::uint32 value);

  // required uint32 b = 3;
  bool has_b() const;
  void clear_b();
  static const int kBFieldNumber = 3;
  ::google::protobuf::uint32 b() const;
  void set_b(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:vss_state.RGB)
 private:
  inline void set_has_r();
  inline void clear_has_r();
  inline void set_has_g();
  inline void clear_has_g();
  inline void set_has_b();
  inline void clear_has_b();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint32 r_;
  ::google::protobuf::uint32 g_;
  ::google::protobuf::uint32 b_;
  friend void  protobuf_AddDesc_state_2eproto();
  friend void protobuf_AssignDesc_state_2eproto();
  friend void protobuf_ShutdownFile_state_2eproto();

  void InitAsDefaultInstance();
  static RGB* default_instance_;
};
// -------------------------------------------------------------------

class Pose : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:vss_state.Pose) */ {
 public:
  Pose();
  virtual ~Pose();

  Pose(const Pose& from);

  inline Pose& operator=(const Pose& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Pose& default_instance();

  void Swap(Pose* other);

  // implements Message ----------------------------------------------

  inline Pose* New() const { return New(NULL); }

  Pose* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Pose& from);
  void MergeFrom(const Pose& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Pose* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required float x = 1;
  bool has_x() const;
  void clear_x();
  static const int kXFieldNumber = 1;
  float x() const;
  void set_x(float value);

  // required float y = 2;
  bool has_y() const;
  void clear_y();
  static const int kYFieldNumber = 2;
  float y() const;
  void set_y(float value);

  // optional float yaw = 3;
  bool has_yaw() const;
  void clear_yaw();
  static const int kYawFieldNumber = 3;
  float yaw() const;
  void set_yaw(float value);

  // @@protoc_insertion_point(class_scope:vss_state.Pose)
 private:
  inline void set_has_x();
  inline void clear_has_x();
  inline void set_has_y();
  inline void clear_has_y();
  inline void set_has_yaw();
  inline void clear_has_yaw();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  float x_;
  float y_;
  float yaw_;
  friend void  protobuf_AddDesc_state_2eproto();
  friend void protobuf_AssignDesc_state_2eproto();
  friend void protobuf_ShutdownFile_state_2eproto();

  void InitAsDefaultInstance();
  static Pose* default_instance_;
};
// -------------------------------------------------------------------

class Ball_State : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:vss_state.Ball_State) */ {
 public:
  Ball_State();
  virtual ~Ball_State();

  Ball_State(const Ball_State& from);

  inline Ball_State& operator=(const Ball_State& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Ball_State& default_instance();

  void Swap(Ball_State* other);

  // implements Message ----------------------------------------------

  inline Ball_State* New() const { return New(NULL); }

  Ball_State* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Ball_State& from);
  void MergeFrom(const Ball_State& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Ball_State* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required .vss_state.Pose pose = 1;
  bool has_pose() const;
  void clear_pose();
  static const int kPoseFieldNumber = 1;
  const ::vss_state::Pose& pose() const;
  ::vss_state::Pose* mutable_pose();
  ::vss_state::Pose* release_pose();
  void set_allocated_pose(::vss_state::Pose* pose);

  // optional .vss_state.Pose v_pose = 2;
  bool has_v_pose() const;
  void clear_v_pose();
  static const int kVPoseFieldNumber = 2;
  const ::vss_state::Pose& v_pose() const;
  ::vss_state::Pose* mutable_v_pose();
  ::vss_state::Pose* release_v_pose();
  void set_allocated_v_pose(::vss_state::Pose* v_pose);

  // optional .vss_state.Pose k_pose = 3;
  bool has_k_pose() const;
  void clear_k_pose();
  static const int kKPoseFieldNumber = 3;
  const ::vss_state::Pose& k_pose() const;
  ::vss_state::Pose* mutable_k_pose();
  ::vss_state::Pose* release_k_pose();
  void set_allocated_k_pose(::vss_state::Pose* k_pose);

  // optional .vss_state.Pose k_v_pose = 4;
  bool has_k_v_pose() const;
  void clear_k_v_pose();
  static const int kKVPoseFieldNumber = 4;
  const ::vss_state::Pose& k_v_pose() const;
  ::vss_state::Pose* mutable_k_v_pose();
  ::vss_state::Pose* release_k_v_pose();
  void set_allocated_k_v_pose(::vss_state::Pose* k_v_pose);

  // @@protoc_insertion_point(class_scope:vss_state.Ball_State)
 private:
  inline void set_has_pose();
  inline void clear_has_pose();
  inline void set_has_v_pose();
  inline void clear_has_v_pose();
  inline void set_has_k_pose();
  inline void clear_has_k_pose();
  inline void set_has_k_v_pose();
  inline void clear_has_k_v_pose();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::vss_state::Pose* pose_;
  ::vss_state::Pose* v_pose_;
  ::vss_state::Pose* k_pose_;
  ::vss_state::Pose* k_v_pose_;
  friend void  protobuf_AddDesc_state_2eproto();
  friend void protobuf_AssignDesc_state_2eproto();
  friend void protobuf_ShutdownFile_state_2eproto();

  void InitAsDefaultInstance();
  static Ball_State* default_instance_;
};
// -------------------------------------------------------------------

class Robot_State : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:vss_state.Robot_State) */ {
 public:
  Robot_State();
  virtual ~Robot_State();

  Robot_State(const Robot_State& from);

  inline Robot_State& operator=(const Robot_State& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Robot_State& default_instance();

  void Swap(Robot_State* other);

  // implements Message ----------------------------------------------

  inline Robot_State* New() const { return New(NULL); }

  Robot_State* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Robot_State& from);
  void MergeFrom(const Robot_State& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Robot_State* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required .vss_state.Pose pose = 1;
  bool has_pose() const;
  void clear_pose();
  static const int kPoseFieldNumber = 1;
  const ::vss_state::Pose& pose() const;
  ::vss_state::Pose* mutable_pose();
  ::vss_state::Pose* release_pose();
  void set_allocated_pose(::vss_state::Pose* pose);

  // optional .vss_state.Pose v_pose = 2;
  bool has_v_pose() const;
  void clear_v_pose();
  static const int kVPoseFieldNumber = 2;
  const ::vss_state::Pose& v_pose() const;
  ::vss_state::Pose* mutable_v_pose();
  ::vss_state::Pose* release_v_pose();
  void set_allocated_v_pose(::vss_state::Pose* v_pose);

  // optional .vss_state.Pose k_pose = 3;
  bool has_k_pose() const;
  void clear_k_pose();
  static const int kKPoseFieldNumber = 3;
  const ::vss_state::Pose& k_pose() const;
  ::vss_state::Pose* mutable_k_pose();
  ::vss_state::Pose* release_k_pose();
  void set_allocated_k_pose(::vss_state::Pose* k_pose);

  // optional .vss_state.Pose k_v_pose = 4;
  bool has_k_v_pose() const;
  void clear_k_v_pose();
  static const int kKVPoseFieldNumber = 4;
  const ::vss_state::Pose& k_v_pose() const;
  ::vss_state::Pose* mutable_k_v_pose();
  ::vss_state::Pose* release_k_v_pose();
  void set_allocated_k_v_pose(::vss_state::Pose* k_v_pose);

  // optional .vss_state.RGB color = 5;
  bool has_color() const;
  void clear_color();
  static const int kColorFieldNumber = 5;
  const ::vss_state::RGB& color() const;
  ::vss_state::RGB* mutable_color();
  ::vss_state::RGB* release_color();
  void set_allocated_color(::vss_state::RGB* color);

  // @@protoc_insertion_point(class_scope:vss_state.Robot_State)
 private:
  inline void set_has_pose();
  inline void clear_has_pose();
  inline void set_has_v_pose();
  inline void clear_has_v_pose();
  inline void set_has_k_pose();
  inline void clear_has_k_pose();
  inline void set_has_k_v_pose();
  inline void clear_has_k_v_pose();
  inline void set_has_color();
  inline void clear_has_color();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::vss_state::Pose* pose_;
  ::vss_state::Pose* v_pose_;
  ::vss_state::Pose* k_pose_;
  ::vss_state::Pose* k_v_pose_;
  ::vss_state::RGB* color_;
  friend void  protobuf_AddDesc_state_2eproto();
  friend void protobuf_AssignDesc_state_2eproto();
  friend void protobuf_ShutdownFile_state_2eproto();

  void InitAsDefaultInstance();
  static Robot_State* default_instance_;
};
// -------------------------------------------------------------------

class Global_State : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:vss_state.Global_State) */ {
 public:
  Global_State();
  virtual ~Global_State();

  Global_State(const Global_State& from);

  inline Global_State& operator=(const Global_State& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Global_State& default_instance();

  void Swap(Global_State* other);

  // implements Message ----------------------------------------------

  inline Global_State* New() const { return New(NULL); }

  Global_State* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Global_State& from);
  void MergeFrom(const Global_State& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Global_State* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 id = 1;
  bool has_id() const;
  void clear_id();
  static const int kIdFieldNumber = 1;
  ::google::protobuf::uint32 id() const;
  void set_id(::google::protobuf::uint32 value);

  // required bool origin = 2;
  bool has_origin() const;
  void clear_origin();
  static const int kOriginFieldNumber = 2;
  bool origin() const;
  void set_origin(bool value);

  // repeated .vss_state.Ball_State balls = 3;
  int balls_size() const;
  void clear_balls();
  static const int kBallsFieldNumber = 3;
  const ::vss_state::Ball_State& balls(int index) const;
  ::vss_state::Ball_State* mutable_balls(int index);
  ::vss_state::Ball_State* add_balls();
  ::google::protobuf::RepeatedPtrField< ::vss_state::Ball_State >*
      mutable_balls();
  const ::google::protobuf::RepeatedPtrField< ::vss_state::Ball_State >&
      balls() const;

  // repeated .vss_state.Robot_State robots_yellow = 4;
  int robots_yellow_size() const;
  void clear_robots_yellow();
  static const int kRobotsYellowFieldNumber = 4;
  const ::vss_state::Robot_State& robots_yellow(int index) const;
  ::vss_state::Robot_State* mutable_robots_yellow(int index);
  ::vss_state::Robot_State* add_robots_yellow();
  ::google::protobuf::RepeatedPtrField< ::vss_state::Robot_State >*
      mutable_robots_yellow();
  const ::google::protobuf::RepeatedPtrField< ::vss_state::Robot_State >&
      robots_yellow() const;

  // repeated .vss_state.Robot_State robots_blue = 5;
  int robots_blue_size() const;
  void clear_robots_blue();
  static const int kRobotsBlueFieldNumber = 5;
  const ::vss_state::Robot_State& robots_blue(int index) const;
  ::vss_state::Robot_State* mutable_robots_blue(int index);
  ::vss_state::Robot_State* add_robots_blue();
  ::google::protobuf::RepeatedPtrField< ::vss_state::Robot_State >*
      mutable_robots_blue();
  const ::google::protobuf::RepeatedPtrField< ::vss_state::Robot_State >&
      robots_blue() const;

  // required uint32 situation = 6;
  bool has_situation() const;
  void clear_situation();
  static const int kSituationFieldNumber = 6;
  ::google::protobuf::uint32 situation() const;
  void set_situation(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:vss_state.Global_State)
 private:
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_origin();
  inline void clear_has_origin();
  inline void set_has_situation();
  inline void clear_has_situation();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint32 id_;
  bool origin_;
  ::google::protobuf::RepeatedPtrField< ::vss_state::Ball_State > balls_;
  ::google::protobuf::RepeatedPtrField< ::vss_state::Robot_State > robots_yellow_;
  ::google::protobuf::RepeatedPtrField< ::vss_state::Robot_State > robots_blue_;
  ::google::protobuf::uint32 situation_;
  friend void  protobuf_AddDesc_state_2eproto();
  friend void protobuf_AssignDesc_state_2eproto();
  friend void protobuf_ShutdownFile_state_2eproto();

  void InitAsDefaultInstance();
  static Global_State* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// RGB

// required uint32 r = 1;
inline bool RGB::has_r() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void RGB::set_has_r() {
  _has_bits_[0] |= 0x00000001u;
}
inline void RGB::clear_has_r() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void RGB::clear_r() {
  r_ = 0u;
  clear_has_r();
}
inline ::google::protobuf::uint32 RGB::r() const {
  // @@protoc_insertion_point(field_get:vss_state.RGB.r)
  return r_;
}
inline void RGB::set_r(::google::protobuf::uint32 value) {
  set_has_r();
  r_ = value;
  // @@protoc_insertion_point(field_set:vss_state.RGB.r)
}

// required uint32 g = 2;
inline bool RGB::has_g() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void RGB::set_has_g() {
  _has_bits_[0] |= 0x00000002u;
}
inline void RGB::clear_has_g() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void RGB::clear_g() {
  g_ = 0u;
  clear_has_g();
}
inline ::google::protobuf::uint32 RGB::g() const {
  // @@protoc_insertion_point(field_get:vss_state.RGB.g)
  return g_;
}
inline void RGB::set_g(::google::protobuf::uint32 value) {
  set_has_g();
  g_ = value;
  // @@protoc_insertion_point(field_set:vss_state.RGB.g)
}

// required uint32 b = 3;
inline bool RGB::has_b() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void RGB::set_has_b() {
  _has_bits_[0] |= 0x00000004u;
}
inline void RGB::clear_has_b() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void RGB::clear_b() {
  b_ = 0u;
  clear_has_b();
}
inline ::google::protobuf::uint32 RGB::b() const {
  // @@protoc_insertion_point(field_get:vss_state.RGB.b)
  return b_;
}
inline void RGB::set_b(::google::protobuf::uint32 value) {
  set_has_b();
  b_ = value;
  // @@protoc_insertion_point(field_set:vss_state.RGB.b)
}

// -------------------------------------------------------------------

// Pose

// required float x = 1;
inline bool Pose::has_x() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Pose::set_has_x() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Pose::clear_has_x() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Pose::clear_x() {
  x_ = 0;
  clear_has_x();
}
inline float Pose::x() const {
  // @@protoc_insertion_point(field_get:vss_state.Pose.x)
  return x_;
}
inline void Pose::set_x(float value) {
  set_has_x();
  x_ = value;
  // @@protoc_insertion_point(field_set:vss_state.Pose.x)
}

// required float y = 2;
inline bool Pose::has_y() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Pose::set_has_y() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Pose::clear_has_y() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Pose::clear_y() {
  y_ = 0;
  clear_has_y();
}
inline float Pose::y() const {
  // @@protoc_insertion_point(field_get:vss_state.Pose.y)
  return y_;
}
inline void Pose::set_y(float value) {
  set_has_y();
  y_ = value;
  // @@protoc_insertion_point(field_set:vss_state.Pose.y)
}

// optional float yaw = 3;
inline bool Pose::has_yaw() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Pose::set_has_yaw() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Pose::clear_has_yaw() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Pose::clear_yaw() {
  yaw_ = 0;
  clear_has_yaw();
}
inline float Pose::yaw() const {
  // @@protoc_insertion_point(field_get:vss_state.Pose.yaw)
  return yaw_;
}
inline void Pose::set_yaw(float value) {
  set_has_yaw();
  yaw_ = value;
  // @@protoc_insertion_point(field_set:vss_state.Pose.yaw)
}

// -------------------------------------------------------------------

// Ball_State

// required .vss_state.Pose pose = 1;
inline bool Ball_State::has_pose() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Ball_State::set_has_pose() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Ball_State::clear_has_pose() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Ball_State::clear_pose() {
  if (pose_ != NULL) pose_->::vss_state::Pose::Clear();
  clear_has_pose();
}
inline const ::vss_state::Pose& Ball_State::pose() const {
  // @@protoc_insertion_point(field_get:vss_state.Ball_State.pose)
  return pose_ != NULL ? *pose_ : *default_instance_->pose_;
}
inline ::vss_state::Pose* Ball_State::mutable_pose() {
  set_has_pose();
  if (pose_ == NULL) {
    pose_ = new ::vss_state::Pose;
  }
  // @@protoc_insertion_point(field_mutable:vss_state.Ball_State.pose)
  return pose_;
}
inline ::vss_state::Pose* Ball_State::release_pose() {
  // @@protoc_insertion_point(field_release:vss_state.Ball_State.pose)
  clear_has_pose();
  ::vss_state::Pose* temp = pose_;
  pose_ = NULL;
  return temp;
}
inline void Ball_State::set_allocated_pose(::vss_state::Pose* pose) {
  delete pose_;
  pose_ = pose;
  if (pose) {
    set_has_pose();
  } else {
    clear_has_pose();
  }
  // @@protoc_insertion_point(field_set_allocated:vss_state.Ball_State.pose)
}

// optional .vss_state.Pose v_pose = 2;
inline bool Ball_State::has_v_pose() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Ball_State::set_has_v_pose() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Ball_State::clear_has_v_pose() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Ball_State::clear_v_pose() {
  if (v_pose_ != NULL) v_pose_->::vss_state::Pose::Clear();
  clear_has_v_pose();
}
inline const ::vss_state::Pose& Ball_State::v_pose() const {
  // @@protoc_insertion_point(field_get:vss_state.Ball_State.v_pose)
  return v_pose_ != NULL ? *v_pose_ : *default_instance_->v_pose_;
}
inline ::vss_state::Pose* Ball_State::mutable_v_pose() {
  set_has_v_pose();
  if (v_pose_ == NULL) {
    v_pose_ = new ::vss_state::Pose;
  }
  // @@protoc_insertion_point(field_mutable:vss_state.Ball_State.v_pose)
  return v_pose_;
}
inline ::vss_state::Pose* Ball_State::release_v_pose() {
  // @@protoc_insertion_point(field_release:vss_state.Ball_State.v_pose)
  clear_has_v_pose();
  ::vss_state::Pose* temp = v_pose_;
  v_pose_ = NULL;
  return temp;
}
inline void Ball_State::set_allocated_v_pose(::vss_state::Pose* v_pose) {
  delete v_pose_;
  v_pose_ = v_pose;
  if (v_pose) {
    set_has_v_pose();
  } else {
    clear_has_v_pose();
  }
  // @@protoc_insertion_point(field_set_allocated:vss_state.Ball_State.v_pose)
}

// optional .vss_state.Pose k_pose = 3;
inline bool Ball_State::has_k_pose() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Ball_State::set_has_k_pose() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Ball_State::clear_has_k_pose() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Ball_State::clear_k_pose() {
  if (k_pose_ != NULL) k_pose_->::vss_state::Pose::Clear();
  clear_has_k_pose();
}
inline const ::vss_state::Pose& Ball_State::k_pose() const {
  // @@protoc_insertion_point(field_get:vss_state.Ball_State.k_pose)
  return k_pose_ != NULL ? *k_pose_ : *default_instance_->k_pose_;
}
inline ::vss_state::Pose* Ball_State::mutable_k_pose() {
  set_has_k_pose();
  if (k_pose_ == NULL) {
    k_pose_ = new ::vss_state::Pose;
  }
  // @@protoc_insertion_point(field_mutable:vss_state.Ball_State.k_pose)
  return k_pose_;
}
inline ::vss_state::Pose* Ball_State::release_k_pose() {
  // @@protoc_insertion_point(field_release:vss_state.Ball_State.k_pose)
  clear_has_k_pose();
  ::vss_state::Pose* temp = k_pose_;
  k_pose_ = NULL;
  return temp;
}
inline void Ball_State::set_allocated_k_pose(::vss_state::Pose* k_pose) {
  delete k_pose_;
  k_pose_ = k_pose;
  if (k_pose) {
    set_has_k_pose();
  } else {
    clear_has_k_pose();
  }
  // @@protoc_insertion_point(field_set_allocated:vss_state.Ball_State.k_pose)
}

// optional .vss_state.Pose k_v_pose = 4;
inline bool Ball_State::has_k_v_pose() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Ball_State::set_has_k_v_pose() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Ball_State::clear_has_k_v_pose() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Ball_State::clear_k_v_pose() {
  if (k_v_pose_ != NULL) k_v_pose_->::vss_state::Pose::Clear();
  clear_has_k_v_pose();
}
inline const ::vss_state::Pose& Ball_State::k_v_pose() const {
  // @@protoc_insertion_point(field_get:vss_state.Ball_State.k_v_pose)
  return k_v_pose_ != NULL ? *k_v_pose_ : *default_instance_->k_v_pose_;
}
inline ::vss_state::Pose* Ball_State::mutable_k_v_pose() {
  set_has_k_v_pose();
  if (k_v_pose_ == NULL) {
    k_v_pose_ = new ::vss_state::Pose;
  }
  // @@protoc_insertion_point(field_mutable:vss_state.Ball_State.k_v_pose)
  return k_v_pose_;
}
inline ::vss_state::Pose* Ball_State::release_k_v_pose() {
  // @@protoc_insertion_point(field_release:vss_state.Ball_State.k_v_pose)
  clear_has_k_v_pose();
  ::vss_state::Pose* temp = k_v_pose_;
  k_v_pose_ = NULL;
  return temp;
}
inline void Ball_State::set_allocated_k_v_pose(::vss_state::Pose* k_v_pose) {
  delete k_v_pose_;
  k_v_pose_ = k_v_pose;
  if (k_v_pose) {
    set_has_k_v_pose();
  } else {
    clear_has_k_v_pose();
  }
  // @@protoc_insertion_point(field_set_allocated:vss_state.Ball_State.k_v_pose)
}

// -------------------------------------------------------------------

// Robot_State

// required .vss_state.Pose pose = 1;
inline bool Robot_State::has_pose() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Robot_State::set_has_pose() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Robot_State::clear_has_pose() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Robot_State::clear_pose() {
  if (pose_ != NULL) pose_->::vss_state::Pose::Clear();
  clear_has_pose();
}
inline const ::vss_state::Pose& Robot_State::pose() const {
  // @@protoc_insertion_point(field_get:vss_state.Robot_State.pose)
  return pose_ != NULL ? *pose_ : *default_instance_->pose_;
}
inline ::vss_state::Pose* Robot_State::mutable_pose() {
  set_has_pose();
  if (pose_ == NULL) {
    pose_ = new ::vss_state::Pose;
  }
  // @@protoc_insertion_point(field_mutable:vss_state.Robot_State.pose)
  return pose_;
}
inline ::vss_state::Pose* Robot_State::release_pose() {
  // @@protoc_insertion_point(field_release:vss_state.Robot_State.pose)
  clear_has_pose();
  ::vss_state::Pose* temp = pose_;
  pose_ = NULL;
  return temp;
}
inline void Robot_State::set_allocated_pose(::vss_state::Pose* pose) {
  delete pose_;
  pose_ = pose;
  if (pose) {
    set_has_pose();
  } else {
    clear_has_pose();
  }
  // @@protoc_insertion_point(field_set_allocated:vss_state.Robot_State.pose)
}

// optional .vss_state.Pose v_pose = 2;
inline bool Robot_State::has_v_pose() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Robot_State::set_has_v_pose() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Robot_State::clear_has_v_pose() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Robot_State::clear_v_pose() {
  if (v_pose_ != NULL) v_pose_->::vss_state::Pose::Clear();
  clear_has_v_pose();
}
inline const ::vss_state::Pose& Robot_State::v_pose() const {
  // @@protoc_insertion_point(field_get:vss_state.Robot_State.v_pose)
  return v_pose_ != NULL ? *v_pose_ : *default_instance_->v_pose_;
}
inline ::vss_state::Pose* Robot_State::mutable_v_pose() {
  set_has_v_pose();
  if (v_pose_ == NULL) {
    v_pose_ = new ::vss_state::Pose;
  }
  // @@protoc_insertion_point(field_mutable:vss_state.Robot_State.v_pose)
  return v_pose_;
}
inline ::vss_state::Pose* Robot_State::release_v_pose() {
  // @@protoc_insertion_point(field_release:vss_state.Robot_State.v_pose)
  clear_has_v_pose();
  ::vss_state::Pose* temp = v_pose_;
  v_pose_ = NULL;
  return temp;
}
inline void Robot_State::set_allocated_v_pose(::vss_state::Pose* v_pose) {
  delete v_pose_;
  v_pose_ = v_pose;
  if (v_pose) {
    set_has_v_pose();
  } else {
    clear_has_v_pose();
  }
  // @@protoc_insertion_point(field_set_allocated:vss_state.Robot_State.v_pose)
}

// optional .vss_state.Pose k_pose = 3;
inline bool Robot_State::has_k_pose() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Robot_State::set_has_k_pose() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Robot_State::clear_has_k_pose() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Robot_State::clear_k_pose() {
  if (k_pose_ != NULL) k_pose_->::vss_state::Pose::Clear();
  clear_has_k_pose();
}
inline const ::vss_state::Pose& Robot_State::k_pose() const {
  // @@protoc_insertion_point(field_get:vss_state.Robot_State.k_pose)
  return k_pose_ != NULL ? *k_pose_ : *default_instance_->k_pose_;
}
inline ::vss_state::Pose* Robot_State::mutable_k_pose() {
  set_has_k_pose();
  if (k_pose_ == NULL) {
    k_pose_ = new ::vss_state::Pose;
  }
  // @@protoc_insertion_point(field_mutable:vss_state.Robot_State.k_pose)
  return k_pose_;
}
inline ::vss_state::Pose* Robot_State::release_k_pose() {
  // @@protoc_insertion_point(field_release:vss_state.Robot_State.k_pose)
  clear_has_k_pose();
  ::vss_state::Pose* temp = k_pose_;
  k_pose_ = NULL;
  return temp;
}
inline void Robot_State::set_allocated_k_pose(::vss_state::Pose* k_pose) {
  delete k_pose_;
  k_pose_ = k_pose;
  if (k_pose) {
    set_has_k_pose();
  } else {
    clear_has_k_pose();
  }
  // @@protoc_insertion_point(field_set_allocated:vss_state.Robot_State.k_pose)
}

// optional .vss_state.Pose k_v_pose = 4;
inline bool Robot_State::has_k_v_pose() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Robot_State::set_has_k_v_pose() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Robot_State::clear_has_k_v_pose() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Robot_State::clear_k_v_pose() {
  if (k_v_pose_ != NULL) k_v_pose_->::vss_state::Pose::Clear();
  clear_has_k_v_pose();
}
inline const ::vss_state::Pose& Robot_State::k_v_pose() const {
  // @@protoc_insertion_point(field_get:vss_state.Robot_State.k_v_pose)
  return k_v_pose_ != NULL ? *k_v_pose_ : *default_instance_->k_v_pose_;
}
inline ::vss_state::Pose* Robot_State::mutable_k_v_pose() {
  set_has_k_v_pose();
  if (k_v_pose_ == NULL) {
    k_v_pose_ = new ::vss_state::Pose;
  }
  // @@protoc_insertion_point(field_mutable:vss_state.Robot_State.k_v_pose)
  return k_v_pose_;
}
inline ::vss_state::Pose* Robot_State::release_k_v_pose() {
  // @@protoc_insertion_point(field_release:vss_state.Robot_State.k_v_pose)
  clear_has_k_v_pose();
  ::vss_state::Pose* temp = k_v_pose_;
  k_v_pose_ = NULL;
  return temp;
}
inline void Robot_State::set_allocated_k_v_pose(::vss_state::Pose* k_v_pose) {
  delete k_v_pose_;
  k_v_pose_ = k_v_pose;
  if (k_v_pose) {
    set_has_k_v_pose();
  } else {
    clear_has_k_v_pose();
  }
  // @@protoc_insertion_point(field_set_allocated:vss_state.Robot_State.k_v_pose)
}

// optional .vss_state.RGB color = 5;
inline bool Robot_State::has_color() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void Robot_State::set_has_color() {
  _has_bits_[0] |= 0x00000010u;
}
inline void Robot_State::clear_has_color() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void Robot_State::clear_color() {
  if (color_ != NULL) color_->::vss_state::RGB::Clear();
  clear_has_color();
}
inline const ::vss_state::RGB& Robot_State::color() const {
  // @@protoc_insertion_point(field_get:vss_state.Robot_State.color)
  return color_ != NULL ? *color_ : *default_instance_->color_;
}
inline ::vss_state::RGB* Robot_State::mutable_color() {
  set_has_color();
  if (color_ == NULL) {
    color_ = new ::vss_state::RGB;
  }
  // @@protoc_insertion_point(field_mutable:vss_state.Robot_State.color)
  return color_;
}
inline ::vss_state::RGB* Robot_State::release_color() {
  // @@protoc_insertion_point(field_release:vss_state.Robot_State.color)
  clear_has_color();
  ::vss_state::RGB* temp = color_;
  color_ = NULL;
  return temp;
}
inline void Robot_State::set_allocated_color(::vss_state::RGB* color) {
  delete color_;
  color_ = color;
  if (color) {
    set_has_color();
  } else {
    clear_has_color();
  }
  // @@protoc_insertion_point(field_set_allocated:vss_state.Robot_State.color)
}

// -------------------------------------------------------------------

// Global_State

// optional uint32 id = 1;
inline bool Global_State::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Global_State::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Global_State::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Global_State::clear_id() {
  id_ = 0u;
  clear_has_id();
}
inline ::google::protobuf::uint32 Global_State::id() const {
  // @@protoc_insertion_point(field_get:vss_state.Global_State.id)
  return id_;
}
inline void Global_State::set_id(::google::protobuf::uint32 value) {
  set_has_id();
  id_ = value;
  // @@protoc_insertion_point(field_set:vss_state.Global_State.id)
}

// required bool origin = 2;
inline bool Global_State::has_origin() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Global_State::set_has_origin() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Global_State::clear_has_origin() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Global_State::clear_origin() {
  origin_ = false;
  clear_has_origin();
}
inline bool Global_State::origin() const {
  // @@protoc_insertion_point(field_get:vss_state.Global_State.origin)
  return origin_;
}
inline void Global_State::set_origin(bool value) {
  set_has_origin();
  origin_ = value;
  // @@protoc_insertion_point(field_set:vss_state.Global_State.origin)
}

// repeated .vss_state.Ball_State balls = 3;
inline int Global_State::balls_size() const {
  return balls_.size();
}
inline void Global_State::clear_balls() {
  balls_.Clear();
}
inline const ::vss_state::Ball_State& Global_State::balls(int index) const {
  // @@protoc_insertion_point(field_get:vss_state.Global_State.balls)
  return balls_.Get(index);
}
inline ::vss_state::Ball_State* Global_State::mutable_balls(int index) {
  // @@protoc_insertion_point(field_mutable:vss_state.Global_State.balls)
  return balls_.Mutable(index);
}
inline ::vss_state::Ball_State* Global_State::add_balls() {
  // @@protoc_insertion_point(field_add:vss_state.Global_State.balls)
  return balls_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::vss_state::Ball_State >*
Global_State::mutable_balls() {
  // @@protoc_insertion_point(field_mutable_list:vss_state.Global_State.balls)
  return &balls_;
}
inline const ::google::protobuf::RepeatedPtrField< ::vss_state::Ball_State >&
Global_State::balls() const {
  // @@protoc_insertion_point(field_list:vss_state.Global_State.balls)
  return balls_;
}

// repeated .vss_state.Robot_State robots_yellow = 4;
inline int Global_State::robots_yellow_size() const {
  return robots_yellow_.size();
}
inline void Global_State::clear_robots_yellow() {
  robots_yellow_.Clear();
}
inline const ::vss_state::Robot_State& Global_State::robots_yellow(int index) const {
  // @@protoc_insertion_point(field_get:vss_state.Global_State.robots_yellow)
  return robots_yellow_.Get(index);
}
inline ::vss_state::Robot_State* Global_State::mutable_robots_yellow(int index) {
  // @@protoc_insertion_point(field_mutable:vss_state.Global_State.robots_yellow)
  return robots_yellow_.Mutable(index);
}
inline ::vss_state::Robot_State* Global_State::add_robots_yellow() {
  // @@protoc_insertion_point(field_add:vss_state.Global_State.robots_yellow)
  return robots_yellow_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::vss_state::Robot_State >*
Global_State::mutable_robots_yellow() {
  // @@protoc_insertion_point(field_mutable_list:vss_state.Global_State.robots_yellow)
  return &robots_yellow_;
}
inline const ::google::protobuf::RepeatedPtrField< ::vss_state::Robot_State >&
Global_State::robots_yellow() const {
  // @@protoc_insertion_point(field_list:vss_state.Global_State.robots_yellow)
  return robots_yellow_;
}

// repeated .vss_state.Robot_State robots_blue = 5;
inline int Global_State::robots_blue_size() const {
  return robots_blue_.size();
}
inline void Global_State::clear_robots_blue() {
  robots_blue_.Clear();
}
inline const ::vss_state::Robot_State& Global_State::robots_blue(int index) const {
  // @@protoc_insertion_point(field_get:vss_state.Global_State.robots_blue)
  return robots_blue_.Get(index);
}
inline ::vss_state::Robot_State* Global_State::mutable_robots_blue(int index) {
  // @@protoc_insertion_point(field_mutable:vss_state.Global_State.robots_blue)
  return robots_blue_.Mutable(index);
}
inline ::vss_state::Robot_State* Global_State::add_robots_blue() {
  // @@protoc_insertion_point(field_add:vss_state.Global_State.robots_blue)
  return robots_blue_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::vss_state::Robot_State >*
Global_State::mutable_robots_blue() {
  // @@protoc_insertion_point(field_mutable_list:vss_state.Global_State.robots_blue)
  return &robots_blue_;
}
inline const ::google::protobuf::RepeatedPtrField< ::vss_state::Robot_State >&
Global_State::robots_blue() const {
  // @@protoc_insertion_point(field_list:vss_state.Global_State.robots_blue)
  return robots_blue_;
}

// required uint32 situation = 6;
inline bool Global_State::has_situation() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void Global_State::set_has_situation() {
  _has_bits_[0] |= 0x00000020u;
}
inline void Global_State::clear_has_situation() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void Global_State::clear_situation() {
  situation_ = 0u;
  clear_has_situation();
}
inline ::google::protobuf::uint32 Global_State::situation() const {
  // @@protoc_insertion_point(field_get:vss_state.Global_State.situation)
  return situation_;
}
inline void Global_State::set_situation(::google::protobuf::uint32 value) {
  set_has_situation();
  situation_ = value;
  // @@protoc_insertion_point(field_set:vss_state.Global_State.situation)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace vss_state

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_state_2eproto__INCLUDED
