// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: command.proto

package vss_command;

public final class Command {
  private Command() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface Robot_CommandOrBuilder extends
      // @@protoc_insertion_point(interface_extends:vss_command.Robot_Command)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required uint32 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required uint32 id = 1;</code>
     */
    int getId();

    /**
     * <code>required float left_vel = 2;</code>
     */
    boolean hasLeftVel();
    /**
     * <code>required float left_vel = 2;</code>
     */
    float getLeftVel();

    /**
     * <code>required float right_vel = 3;</code>
     */
    boolean hasRightVel();
    /**
     * <code>required float right_vel = 3;</code>
     */
    float getRightVel();
  }
  /**
   * Protobuf type {@code vss_command.Robot_Command}
   */
  public  static final class Robot_Command extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:vss_command.Robot_Command)
      Robot_CommandOrBuilder {
    // Use Robot_Command.newBuilder() to construct.
    private Robot_Command(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Robot_Command() {
      id_ = 0;
      leftVel_ = 0F;
      rightVel_ = 0F;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Robot_Command(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readUInt32();
              break;
            }
            case 21: {
              bitField0_ |= 0x00000002;
              leftVel_ = input.readFloat();
              break;
            }
            case 29: {
              bitField0_ |= 0x00000004;
              rightVel_ = input.readFloat();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return vss_command.Command.internal_static_vss_command_Robot_Command_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return vss_command.Command.internal_static_vss_command_Robot_Command_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              vss_command.Command.Robot_Command.class, vss_command.Command.Robot_Command.Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>required uint32 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int LEFT_VEL_FIELD_NUMBER = 2;
    private float leftVel_;
    /**
     * <code>required float left_vel = 2;</code>
     */
    public boolean hasLeftVel() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required float left_vel = 2;</code>
     */
    public float getLeftVel() {
      return leftVel_;
    }

    public static final int RIGHT_VEL_FIELD_NUMBER = 3;
    private float rightVel_;
    /**
     * <code>required float right_vel = 3;</code>
     */
    public boolean hasRightVel() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required float right_vel = 3;</code>
     */
    public float getRightVel() {
      return rightVel_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLeftVel()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRightVel()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeFloat(2, leftVel_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeFloat(3, rightVel_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, leftVel_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, rightVel_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof vss_command.Command.Robot_Command)) {
        return super.equals(obj);
      }
      vss_command.Command.Robot_Command other = (vss_command.Command.Robot_Command) obj;

      boolean result = true;
      result = result && (hasId() == other.hasId());
      if (hasId()) {
        result = result && (getId()
            == other.getId());
      }
      result = result && (hasLeftVel() == other.hasLeftVel());
      if (hasLeftVel()) {
        result = result && (
            java.lang.Float.floatToIntBits(getLeftVel())
            == java.lang.Float.floatToIntBits(
                other.getLeftVel()));
      }
      result = result && (hasRightVel() == other.hasRightVel());
      if (hasRightVel()) {
        result = result && (
            java.lang.Float.floatToIntBits(getRightVel())
            == java.lang.Float.floatToIntBits(
                other.getRightVel()));
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasId()) {
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + getId();
      }
      if (hasLeftVel()) {
        hash = (37 * hash) + LEFT_VEL_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(
            getLeftVel());
      }
      if (hasRightVel()) {
        hash = (37 * hash) + RIGHT_VEL_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(
            getRightVel());
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static vss_command.Command.Robot_Command parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static vss_command.Command.Robot_Command parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static vss_command.Command.Robot_Command parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static vss_command.Command.Robot_Command parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static vss_command.Command.Robot_Command parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static vss_command.Command.Robot_Command parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static vss_command.Command.Robot_Command parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static vss_command.Command.Robot_Command parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static vss_command.Command.Robot_Command parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static vss_command.Command.Robot_Command parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(vss_command.Command.Robot_Command prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code vss_command.Robot_Command}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:vss_command.Robot_Command)
        vss_command.Command.Robot_CommandOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return vss_command.Command.internal_static_vss_command_Robot_Command_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return vss_command.Command.internal_static_vss_command_Robot_Command_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                vss_command.Command.Robot_Command.class, vss_command.Command.Robot_Command.Builder.class);
      }

      // Construct using vss_command.Command.Robot_Command.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        leftVel_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000002);
        rightVel_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return vss_command.Command.internal_static_vss_command_Robot_Command_descriptor;
      }

      public vss_command.Command.Robot_Command getDefaultInstanceForType() {
        return vss_command.Command.Robot_Command.getDefaultInstance();
      }

      public vss_command.Command.Robot_Command build() {
        vss_command.Command.Robot_Command result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public vss_command.Command.Robot_Command buildPartial() {
        vss_command.Command.Robot_Command result = new vss_command.Command.Robot_Command(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.leftVel_ = leftVel_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.rightVel_ = rightVel_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof vss_command.Command.Robot_Command) {
          return mergeFrom((vss_command.Command.Robot_Command)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(vss_command.Command.Robot_Command other) {
        if (other == vss_command.Command.Robot_Command.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasLeftVel()) {
          setLeftVel(other.getLeftVel());
        }
        if (other.hasRightVel()) {
          setRightVel(other.getRightVel());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          return false;
        }
        if (!hasLeftVel()) {
          return false;
        }
        if (!hasRightVel()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        vss_command.Command.Robot_Command parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (vss_command.Command.Robot_Command) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>required uint32 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>required uint32 id = 1;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      private float leftVel_ ;
      /**
       * <code>required float left_vel = 2;</code>
       */
      public boolean hasLeftVel() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required float left_vel = 2;</code>
       */
      public float getLeftVel() {
        return leftVel_;
      }
      /**
       * <code>required float left_vel = 2;</code>
       */
      public Builder setLeftVel(float value) {
        bitField0_ |= 0x00000002;
        leftVel_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float left_vel = 2;</code>
       */
      public Builder clearLeftVel() {
        bitField0_ = (bitField0_ & ~0x00000002);
        leftVel_ = 0F;
        onChanged();
        return this;
      }

      private float rightVel_ ;
      /**
       * <code>required float right_vel = 3;</code>
       */
      public boolean hasRightVel() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required float right_vel = 3;</code>
       */
      public float getRightVel() {
        return rightVel_;
      }
      /**
       * <code>required float right_vel = 3;</code>
       */
      public Builder setRightVel(float value) {
        bitField0_ |= 0x00000004;
        rightVel_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float right_vel = 3;</code>
       */
      public Builder clearRightVel() {
        bitField0_ = (bitField0_ & ~0x00000004);
        rightVel_ = 0F;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:vss_command.Robot_Command)
    }

    // @@protoc_insertion_point(class_scope:vss_command.Robot_Command)
    private static final vss_command.Command.Robot_Command DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new vss_command.Command.Robot_Command();
    }

    public static vss_command.Command.Robot_Command getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Robot_Command>
        PARSER = new com.google.protobuf.AbstractParser<Robot_Command>() {
      public Robot_Command parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Robot_Command(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Robot_Command> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Robot_Command> getParserForType() {
      return PARSER;
    }

    public vss_command.Command.Robot_Command getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface Global_CommandsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:vss_command.Global_Commands)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional uint32 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>optional uint32 id = 1;</code>
     */
    int getId();

    /**
     * <code>required bool is_team_yellow = 2;</code>
     */
    boolean hasIsTeamYellow();
    /**
     * <code>required bool is_team_yellow = 2;</code>
     */
    boolean getIsTeamYellow();

    /**
     * <code>repeated .vss_command.Robot_Command robot_commands = 3;</code>
     */
    java.util.List<vss_command.Command.Robot_Command> 
        getRobotCommandsList();
    /**
     * <code>repeated .vss_command.Robot_Command robot_commands = 3;</code>
     */
    vss_command.Command.Robot_Command getRobotCommands(int index);
    /**
     * <code>repeated .vss_command.Robot_Command robot_commands = 3;</code>
     */
    int getRobotCommandsCount();
    /**
     * <code>repeated .vss_command.Robot_Command robot_commands = 3;</code>
     */
    java.util.List<? extends vss_command.Command.Robot_CommandOrBuilder> 
        getRobotCommandsOrBuilderList();
    /**
     * <code>repeated .vss_command.Robot_Command robot_commands = 3;</code>
     */
    vss_command.Command.Robot_CommandOrBuilder getRobotCommandsOrBuilder(
        int index);

    /**
     * <pre>
     * SITUATIONS
     *0 = Normal Game
     *1 = Re-organize (GOAL_TEAM1)
     *2 = Re-organize (GOAL_TEAM2)
     *3 = Re-organize (FAULT_TEAM1)
     *4 = Re-organize (FAULT_TEAM2)
     *5 = Re-organize (PENALTY_TEAM1)
     *6 = Re-organize (PENALITY_TEAM2)
     *99 = Finish
     * </pre>
     *
     * <code>required uint32 situation = 4;</code>
     */
    boolean hasSituation();
    /**
     * <pre>
     * SITUATIONS
     *0 = Normal Game
     *1 = Re-organize (GOAL_TEAM1)
     *2 = Re-organize (GOAL_TEAM2)
     *3 = Re-organize (FAULT_TEAM1)
     *4 = Re-organize (FAULT_TEAM2)
     *5 = Re-organize (PENALTY_TEAM1)
     *6 = Re-organize (PENALITY_TEAM2)
     *99 = Finish
     * </pre>
     *
     * <code>required uint32 situation = 4;</code>
     */
    int getSituation();
  }
  /**
   * Protobuf type {@code vss_command.Global_Commands}
   */
  public  static final class Global_Commands extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:vss_command.Global_Commands)
      Global_CommandsOrBuilder {
    // Use Global_Commands.newBuilder() to construct.
    private Global_Commands(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Global_Commands() {
      id_ = 0;
      isTeamYellow_ = false;
      robotCommands_ = java.util.Collections.emptyList();
      situation_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Global_Commands(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readUInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              isTeamYellow_ = input.readBool();
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                robotCommands_ = new java.util.ArrayList<vss_command.Command.Robot_Command>();
                mutable_bitField0_ |= 0x00000004;
              }
              robotCommands_.add(
                  input.readMessage(vss_command.Command.Robot_Command.PARSER, extensionRegistry));
              break;
            }
            case 32: {
              bitField0_ |= 0x00000004;
              situation_ = input.readUInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          robotCommands_ = java.util.Collections.unmodifiableList(robotCommands_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return vss_command.Command.internal_static_vss_command_Global_Commands_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return vss_command.Command.internal_static_vss_command_Global_Commands_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              vss_command.Command.Global_Commands.class, vss_command.Command.Global_Commands.Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>optional uint32 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional uint32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int IS_TEAM_YELLOW_FIELD_NUMBER = 2;
    private boolean isTeamYellow_;
    /**
     * <code>required bool is_team_yellow = 2;</code>
     */
    public boolean hasIsTeamYellow() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required bool is_team_yellow = 2;</code>
     */
    public boolean getIsTeamYellow() {
      return isTeamYellow_;
    }

    public static final int ROBOT_COMMANDS_FIELD_NUMBER = 3;
    private java.util.List<vss_command.Command.Robot_Command> robotCommands_;
    /**
     * <code>repeated .vss_command.Robot_Command robot_commands = 3;</code>
     */
    public java.util.List<vss_command.Command.Robot_Command> getRobotCommandsList() {
      return robotCommands_;
    }
    /**
     * <code>repeated .vss_command.Robot_Command robot_commands = 3;</code>
     */
    public java.util.List<? extends vss_command.Command.Robot_CommandOrBuilder> 
        getRobotCommandsOrBuilderList() {
      return robotCommands_;
    }
    /**
     * <code>repeated .vss_command.Robot_Command robot_commands = 3;</code>
     */
    public int getRobotCommandsCount() {
      return robotCommands_.size();
    }
    /**
     * <code>repeated .vss_command.Robot_Command robot_commands = 3;</code>
     */
    public vss_command.Command.Robot_Command getRobotCommands(int index) {
      return robotCommands_.get(index);
    }
    /**
     * <code>repeated .vss_command.Robot_Command robot_commands = 3;</code>
     */
    public vss_command.Command.Robot_CommandOrBuilder getRobotCommandsOrBuilder(
        int index) {
      return robotCommands_.get(index);
    }

    public static final int SITUATION_FIELD_NUMBER = 4;
    private int situation_;
    /**
     * <pre>
     * SITUATIONS
     *0 = Normal Game
     *1 = Re-organize (GOAL_TEAM1)
     *2 = Re-organize (GOAL_TEAM2)
     *3 = Re-organize (FAULT_TEAM1)
     *4 = Re-organize (FAULT_TEAM2)
     *5 = Re-organize (PENALTY_TEAM1)
     *6 = Re-organize (PENALITY_TEAM2)
     *99 = Finish
     * </pre>
     *
     * <code>required uint32 situation = 4;</code>
     */
    public boolean hasSituation() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <pre>
     * SITUATIONS
     *0 = Normal Game
     *1 = Re-organize (GOAL_TEAM1)
     *2 = Re-organize (GOAL_TEAM2)
     *3 = Re-organize (FAULT_TEAM1)
     *4 = Re-organize (FAULT_TEAM2)
     *5 = Re-organize (PENALTY_TEAM1)
     *6 = Re-organize (PENALITY_TEAM2)
     *99 = Finish
     * </pre>
     *
     * <code>required uint32 situation = 4;</code>
     */
    public int getSituation() {
      return situation_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasIsTeamYellow()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSituation()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getRobotCommandsCount(); i++) {
        if (!getRobotCommands(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBool(2, isTeamYellow_);
      }
      for (int i = 0; i < robotCommands_.size(); i++) {
        output.writeMessage(3, robotCommands_.get(i));
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeUInt32(4, situation_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, isTeamYellow_);
      }
      for (int i = 0; i < robotCommands_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, robotCommands_.get(i));
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, situation_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof vss_command.Command.Global_Commands)) {
        return super.equals(obj);
      }
      vss_command.Command.Global_Commands other = (vss_command.Command.Global_Commands) obj;

      boolean result = true;
      result = result && (hasId() == other.hasId());
      if (hasId()) {
        result = result && (getId()
            == other.getId());
      }
      result = result && (hasIsTeamYellow() == other.hasIsTeamYellow());
      if (hasIsTeamYellow()) {
        result = result && (getIsTeamYellow()
            == other.getIsTeamYellow());
      }
      result = result && getRobotCommandsList()
          .equals(other.getRobotCommandsList());
      result = result && (hasSituation() == other.hasSituation());
      if (hasSituation()) {
        result = result && (getSituation()
            == other.getSituation());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasId()) {
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + getId();
      }
      if (hasIsTeamYellow()) {
        hash = (37 * hash) + IS_TEAM_YELLOW_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getIsTeamYellow());
      }
      if (getRobotCommandsCount() > 0) {
        hash = (37 * hash) + ROBOT_COMMANDS_FIELD_NUMBER;
        hash = (53 * hash) + getRobotCommandsList().hashCode();
      }
      if (hasSituation()) {
        hash = (37 * hash) + SITUATION_FIELD_NUMBER;
        hash = (53 * hash) + getSituation();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static vss_command.Command.Global_Commands parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static vss_command.Command.Global_Commands parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static vss_command.Command.Global_Commands parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static vss_command.Command.Global_Commands parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static vss_command.Command.Global_Commands parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static vss_command.Command.Global_Commands parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static vss_command.Command.Global_Commands parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static vss_command.Command.Global_Commands parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static vss_command.Command.Global_Commands parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static vss_command.Command.Global_Commands parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(vss_command.Command.Global_Commands prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code vss_command.Global_Commands}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:vss_command.Global_Commands)
        vss_command.Command.Global_CommandsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return vss_command.Command.internal_static_vss_command_Global_Commands_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return vss_command.Command.internal_static_vss_command_Global_Commands_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                vss_command.Command.Global_Commands.class, vss_command.Command.Global_Commands.Builder.class);
      }

      // Construct using vss_command.Command.Global_Commands.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getRobotCommandsFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        isTeamYellow_ = false;
        bitField0_ = (bitField0_ & ~0x00000002);
        if (robotCommandsBuilder_ == null) {
          robotCommands_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          robotCommandsBuilder_.clear();
        }
        situation_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return vss_command.Command.internal_static_vss_command_Global_Commands_descriptor;
      }

      public vss_command.Command.Global_Commands getDefaultInstanceForType() {
        return vss_command.Command.Global_Commands.getDefaultInstance();
      }

      public vss_command.Command.Global_Commands build() {
        vss_command.Command.Global_Commands result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public vss_command.Command.Global_Commands buildPartial() {
        vss_command.Command.Global_Commands result = new vss_command.Command.Global_Commands(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.isTeamYellow_ = isTeamYellow_;
        if (robotCommandsBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            robotCommands_ = java.util.Collections.unmodifiableList(robotCommands_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.robotCommands_ = robotCommands_;
        } else {
          result.robotCommands_ = robotCommandsBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000004;
        }
        result.situation_ = situation_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof vss_command.Command.Global_Commands) {
          return mergeFrom((vss_command.Command.Global_Commands)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(vss_command.Command.Global_Commands other) {
        if (other == vss_command.Command.Global_Commands.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasIsTeamYellow()) {
          setIsTeamYellow(other.getIsTeamYellow());
        }
        if (robotCommandsBuilder_ == null) {
          if (!other.robotCommands_.isEmpty()) {
            if (robotCommands_.isEmpty()) {
              robotCommands_ = other.robotCommands_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureRobotCommandsIsMutable();
              robotCommands_.addAll(other.robotCommands_);
            }
            onChanged();
          }
        } else {
          if (!other.robotCommands_.isEmpty()) {
            if (robotCommandsBuilder_.isEmpty()) {
              robotCommandsBuilder_.dispose();
              robotCommandsBuilder_ = null;
              robotCommands_ = other.robotCommands_;
              bitField0_ = (bitField0_ & ~0x00000004);
              robotCommandsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getRobotCommandsFieldBuilder() : null;
            } else {
              robotCommandsBuilder_.addAllMessages(other.robotCommands_);
            }
          }
        }
        if (other.hasSituation()) {
          setSituation(other.getSituation());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasIsTeamYellow()) {
          return false;
        }
        if (!hasSituation()) {
          return false;
        }
        for (int i = 0; i < getRobotCommandsCount(); i++) {
          if (!getRobotCommands(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        vss_command.Command.Global_Commands parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (vss_command.Command.Global_Commands) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>optional uint32 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional uint32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>optional uint32 id = 1;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      private boolean isTeamYellow_ ;
      /**
       * <code>required bool is_team_yellow = 2;</code>
       */
      public boolean hasIsTeamYellow() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required bool is_team_yellow = 2;</code>
       */
      public boolean getIsTeamYellow() {
        return isTeamYellow_;
      }
      /**
       * <code>required bool is_team_yellow = 2;</code>
       */
      public Builder setIsTeamYellow(boolean value) {
        bitField0_ |= 0x00000002;
        isTeamYellow_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool is_team_yellow = 2;</code>
       */
      public Builder clearIsTeamYellow() {
        bitField0_ = (bitField0_ & ~0x00000002);
        isTeamYellow_ = false;
        onChanged();
        return this;
      }

      private java.util.List<vss_command.Command.Robot_Command> robotCommands_ =
        java.util.Collections.emptyList();
      private void ensureRobotCommandsIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          robotCommands_ = new java.util.ArrayList<vss_command.Command.Robot_Command>(robotCommands_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          vss_command.Command.Robot_Command, vss_command.Command.Robot_Command.Builder, vss_command.Command.Robot_CommandOrBuilder> robotCommandsBuilder_;

      /**
       * <code>repeated .vss_command.Robot_Command robot_commands = 3;</code>
       */
      public java.util.List<vss_command.Command.Robot_Command> getRobotCommandsList() {
        if (robotCommandsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(robotCommands_);
        } else {
          return robotCommandsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .vss_command.Robot_Command robot_commands = 3;</code>
       */
      public int getRobotCommandsCount() {
        if (robotCommandsBuilder_ == null) {
          return robotCommands_.size();
        } else {
          return robotCommandsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .vss_command.Robot_Command robot_commands = 3;</code>
       */
      public vss_command.Command.Robot_Command getRobotCommands(int index) {
        if (robotCommandsBuilder_ == null) {
          return robotCommands_.get(index);
        } else {
          return robotCommandsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .vss_command.Robot_Command robot_commands = 3;</code>
       */
      public Builder setRobotCommands(
          int index, vss_command.Command.Robot_Command value) {
        if (robotCommandsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRobotCommandsIsMutable();
          robotCommands_.set(index, value);
          onChanged();
        } else {
          robotCommandsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .vss_command.Robot_Command robot_commands = 3;</code>
       */
      public Builder setRobotCommands(
          int index, vss_command.Command.Robot_Command.Builder builderForValue) {
        if (robotCommandsBuilder_ == null) {
          ensureRobotCommandsIsMutable();
          robotCommands_.set(index, builderForValue.build());
          onChanged();
        } else {
          robotCommandsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .vss_command.Robot_Command robot_commands = 3;</code>
       */
      public Builder addRobotCommands(vss_command.Command.Robot_Command value) {
        if (robotCommandsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRobotCommandsIsMutable();
          robotCommands_.add(value);
          onChanged();
        } else {
          robotCommandsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .vss_command.Robot_Command robot_commands = 3;</code>
       */
      public Builder addRobotCommands(
          int index, vss_command.Command.Robot_Command value) {
        if (robotCommandsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRobotCommandsIsMutable();
          robotCommands_.add(index, value);
          onChanged();
        } else {
          robotCommandsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .vss_command.Robot_Command robot_commands = 3;</code>
       */
      public Builder addRobotCommands(
          vss_command.Command.Robot_Command.Builder builderForValue) {
        if (robotCommandsBuilder_ == null) {
          ensureRobotCommandsIsMutable();
          robotCommands_.add(builderForValue.build());
          onChanged();
        } else {
          robotCommandsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .vss_command.Robot_Command robot_commands = 3;</code>
       */
      public Builder addRobotCommands(
          int index, vss_command.Command.Robot_Command.Builder builderForValue) {
        if (robotCommandsBuilder_ == null) {
          ensureRobotCommandsIsMutable();
          robotCommands_.add(index, builderForValue.build());
          onChanged();
        } else {
          robotCommandsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .vss_command.Robot_Command robot_commands = 3;</code>
       */
      public Builder addAllRobotCommands(
          java.lang.Iterable<? extends vss_command.Command.Robot_Command> values) {
        if (robotCommandsBuilder_ == null) {
          ensureRobotCommandsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, robotCommands_);
          onChanged();
        } else {
          robotCommandsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .vss_command.Robot_Command robot_commands = 3;</code>
       */
      public Builder clearRobotCommands() {
        if (robotCommandsBuilder_ == null) {
          robotCommands_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          robotCommandsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .vss_command.Robot_Command robot_commands = 3;</code>
       */
      public Builder removeRobotCommands(int index) {
        if (robotCommandsBuilder_ == null) {
          ensureRobotCommandsIsMutable();
          robotCommands_.remove(index);
          onChanged();
        } else {
          robotCommandsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .vss_command.Robot_Command robot_commands = 3;</code>
       */
      public vss_command.Command.Robot_Command.Builder getRobotCommandsBuilder(
          int index) {
        return getRobotCommandsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .vss_command.Robot_Command robot_commands = 3;</code>
       */
      public vss_command.Command.Robot_CommandOrBuilder getRobotCommandsOrBuilder(
          int index) {
        if (robotCommandsBuilder_ == null) {
          return robotCommands_.get(index);  } else {
          return robotCommandsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .vss_command.Robot_Command robot_commands = 3;</code>
       */
      public java.util.List<? extends vss_command.Command.Robot_CommandOrBuilder> 
           getRobotCommandsOrBuilderList() {
        if (robotCommandsBuilder_ != null) {
          return robotCommandsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(robotCommands_);
        }
      }
      /**
       * <code>repeated .vss_command.Robot_Command robot_commands = 3;</code>
       */
      public vss_command.Command.Robot_Command.Builder addRobotCommandsBuilder() {
        return getRobotCommandsFieldBuilder().addBuilder(
            vss_command.Command.Robot_Command.getDefaultInstance());
      }
      /**
       * <code>repeated .vss_command.Robot_Command robot_commands = 3;</code>
       */
      public vss_command.Command.Robot_Command.Builder addRobotCommandsBuilder(
          int index) {
        return getRobotCommandsFieldBuilder().addBuilder(
            index, vss_command.Command.Robot_Command.getDefaultInstance());
      }
      /**
       * <code>repeated .vss_command.Robot_Command robot_commands = 3;</code>
       */
      public java.util.List<vss_command.Command.Robot_Command.Builder> 
           getRobotCommandsBuilderList() {
        return getRobotCommandsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          vss_command.Command.Robot_Command, vss_command.Command.Robot_Command.Builder, vss_command.Command.Robot_CommandOrBuilder> 
          getRobotCommandsFieldBuilder() {
        if (robotCommandsBuilder_ == null) {
          robotCommandsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              vss_command.Command.Robot_Command, vss_command.Command.Robot_Command.Builder, vss_command.Command.Robot_CommandOrBuilder>(
                  robotCommands_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          robotCommands_ = null;
        }
        return robotCommandsBuilder_;
      }

      private int situation_ ;
      /**
       * <pre>
       * SITUATIONS
       *0 = Normal Game
       *1 = Re-organize (GOAL_TEAM1)
       *2 = Re-organize (GOAL_TEAM2)
       *3 = Re-organize (FAULT_TEAM1)
       *4 = Re-organize (FAULT_TEAM2)
       *5 = Re-organize (PENALTY_TEAM1)
       *6 = Re-organize (PENALITY_TEAM2)
       *99 = Finish
       * </pre>
       *
       * <code>required uint32 situation = 4;</code>
       */
      public boolean hasSituation() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <pre>
       * SITUATIONS
       *0 = Normal Game
       *1 = Re-organize (GOAL_TEAM1)
       *2 = Re-organize (GOAL_TEAM2)
       *3 = Re-organize (FAULT_TEAM1)
       *4 = Re-organize (FAULT_TEAM2)
       *5 = Re-organize (PENALTY_TEAM1)
       *6 = Re-organize (PENALITY_TEAM2)
       *99 = Finish
       * </pre>
       *
       * <code>required uint32 situation = 4;</code>
       */
      public int getSituation() {
        return situation_;
      }
      /**
       * <pre>
       * SITUATIONS
       *0 = Normal Game
       *1 = Re-organize (GOAL_TEAM1)
       *2 = Re-organize (GOAL_TEAM2)
       *3 = Re-organize (FAULT_TEAM1)
       *4 = Re-organize (FAULT_TEAM2)
       *5 = Re-organize (PENALTY_TEAM1)
       *6 = Re-organize (PENALITY_TEAM2)
       *99 = Finish
       * </pre>
       *
       * <code>required uint32 situation = 4;</code>
       */
      public Builder setSituation(int value) {
        bitField0_ |= 0x00000008;
        situation_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * SITUATIONS
       *0 = Normal Game
       *1 = Re-organize (GOAL_TEAM1)
       *2 = Re-organize (GOAL_TEAM2)
       *3 = Re-organize (FAULT_TEAM1)
       *4 = Re-organize (FAULT_TEAM2)
       *5 = Re-organize (PENALTY_TEAM1)
       *6 = Re-organize (PENALITY_TEAM2)
       *99 = Finish
       * </pre>
       *
       * <code>required uint32 situation = 4;</code>
       */
      public Builder clearSituation() {
        bitField0_ = (bitField0_ & ~0x00000008);
        situation_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:vss_command.Global_Commands)
    }

    // @@protoc_insertion_point(class_scope:vss_command.Global_Commands)
    private static final vss_command.Command.Global_Commands DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new vss_command.Command.Global_Commands();
    }

    public static vss_command.Command.Global_Commands getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Global_Commands>
        PARSER = new com.google.protobuf.AbstractParser<Global_Commands>() {
      public Global_Commands parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Global_Commands(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Global_Commands> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Global_Commands> getParserForType() {
      return PARSER;
    }

    public vss_command.Command.Global_Commands getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_vss_command_Robot_Command_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_vss_command_Robot_Command_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_vss_command_Global_Commands_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_vss_command_Global_Commands_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rcommand.proto\022\013vss_command\"@\n\rRobot_Co" +
      "mmand\022\n\n\002id\030\001 \002(\r\022\020\n\010left_vel\030\002 \002(\002\022\021\n\tr" +
      "ight_vel\030\003 \002(\002\"|\n\017Global_Commands\022\n\n\002id\030" +
      "\001 \001(\r\022\026\n\016is_team_yellow\030\002 \002(\010\0222\n\016robot_c" +
      "ommands\030\003 \003(\0132\032.vss_command.Robot_Comman" +
      "d\022\021\n\tsituation\030\004 \002(\r"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_vss_command_Robot_Command_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_vss_command_Robot_Command_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_vss_command_Robot_Command_descriptor,
        new java.lang.String[] { "Id", "LeftVel", "RightVel", });
    internal_static_vss_command_Global_Commands_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_vss_command_Global_Commands_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_vss_command_Global_Commands_descriptor,
        new java.lang.String[] { "Id", "IsTeamYellow", "RobotCommands", "Situation", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
